version: '3.3'

services:
  uprodit_vue:
    restart: always
    container_name: uprodit_vue
    image: rg.fr-par.scw.cloud/prodit/uprodit_vue:${VERSION}
    networks:
      - uprodit_vue
    ports:
      - "5337:80"

networks:
  uprodit_vue:
    driver: bridge
